# Generated by Django 4.2.4 on 2024-02-10 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_alter_state_created_date_alter_state_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 15, 1, 19, 242337)),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 15, 1, 19, 242337)),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 15, 1, 19, 245347)),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tickets.state'),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 15, 1, 19, 245347)),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 15, 1, 19, 243355)),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tickets.state'),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 15, 1, 19, 243355)),
        ),
    ]
